// The preview page in a web view with JavaScript on, because the page carries the small Web Audio synth.
// The page is generated by SclCore and loads nothing remote. The page reports octave / tuning changes through the
// "synth" message handler, and the web view reports when it has finished showing a page.
import SwiftUI
import WebKit
#if os(iOS)
import AVFoundation
#endif

@MainActor
final class WebCoordinator: NSObject, WKNavigationDelegate, WKScriptMessageHandler {
    var html: String?
    var onFinish: () -> Void = {}
    var onSynth: (Double, Int) -> Void = { _, _ in }
    var onAudio: (Int) -> Void = { _ in }

    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        Task { @MainActor in self.onFinish() }          // never inside a view update
    }
    func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) { finishUnlessCancelled(error) }
    func webView(_ webView: WKWebView, didFailProvisionalNavigation navigation: WKNavigation!, withError error: Error) { finishUnlessCancelled(error) }

    private func finishUnlessCancelled(_ error: Error) {
        if (error as NSError).code != NSURLErrorCancelled { onFinish() }
    }

    func userContentController(_ controller: WKUserContentController, didReceive message: WKScriptMessage) {
        guard let body = message.body as? [String: Any] else { return }
        if let ms = (body["audioMs"] as? NSNumber)?.intValue { onAudio(ms); return }
        guard let ref = (body["ref"] as? NSNumber)?.doubleValue,
              let oct = (body["oct"] as? NSNumber)?.intValue else { return }
        onSynth(ref, oct)
    }
}

@MainActor
private func makeWebView(_ coordinator: WebCoordinator) -> WKWebView {
    let config = WKWebViewConfiguration()
    config.defaultWebpagePreferences.allowsContentJavaScript = true
    config.userContentController.add(coordinator, name: "synth")
    let view = WKWebView(frame: .zero, configuration: config)
    view.navigationDelegate = coordinator
    return view
}

@MainActor
private func update(_ view: WKWebView, _ coordinator: WebCoordinator, html: String,
                    onFinish: @escaping () -> Void, onSynth: @escaping (Double, Int) -> Void,
                    onAudio: @escaping (Int) -> Void) {
    coordinator.onFinish = onFinish
    coordinator.onSynth = onSynth
    coordinator.onAudio = onAudio
    guard coordinator.html != html else { return }
    coordinator.html = html
    view.loadHTMLString(html, baseURL: nil)
}

#if os(macOS)
struct ScaleWebView: NSViewRepresentable {
    let html: String
    let onFinish: () -> Void
    let onSynth: (Double, Int) -> Void
    let onAudio: (Int) -> Void

    func makeCoordinator() -> WebCoordinator { WebCoordinator() }
    func makeNSView(context: Context) -> WKWebView {
        let view = makeWebView(context.coordinator)
        view.allowsMagnification = false          // no pinch or double-tap zoom: the page keeps its size
        return view
    }
    func updateNSView(_ view: WKWebView, context: Context) {
        update(view, context.coordinator, html: html, onFinish: onFinish, onSynth: onSynth, onAudio: onAudio)
    }
}
#else
struct ScaleWebView: UIViewRepresentable {
    let html: String
    let onFinish: () -> Void
    let onSynth: (Double, Int) -> Void
    let onAudio: (Int) -> Void

    func makeCoordinator() -> WebCoordinator { WebCoordinator() }
    func makeUIView(context: Context) -> WKWebView {
        // .playback lets the synth sound with the ringer switch on silent, as a music app would.
        DispatchQueue.global(qos: .utility).async { try? AVAudioSession.sharedInstance().setCategory(.playback) }
        let view = makeWebView(context.coordinator)
        view.scrollView.pinchGestureRecognizer?.isEnabled = false   // no pinch zoom
        view.scrollView.minimumZoomScale = 1
        view.scrollView.maximumZoomScale = 1
        view.isOpaque = false
        view.backgroundColor = .clear
        return view
    }
    func updateUIView(_ view: WKWebView, context: Context) {
        update(view, context.coordinator, html: html, onFinish: onFinish, onSynth: onSynth, onAudio: onAudio)
    }
}
#endif
