# Shared settings and helpers. Sourced by the other scripts; not meant to be run directly.

# The scripts live in <repo>/Scripts; everything else (project.yml, version.env, Bundle/, ...) is relative to <repo>.
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPTS_DIR/.." && pwd)"

cd "$ROOT"

# Version/build come from version.env; an environment variable wins if set.
_v="${VERSION:-}"; _b="${BUILD:-}"
# shellcheck source=version.env
source "$ROOT/version.env"
VERSION="${_v:-$VERSION}"; BUILD="${_b:-$BUILD}"
unset _v _b

BUNDLE_ID="${BUNDLE_ID:-com.alexnadzharov.xenscalepreview}"   # the extension gets "$BUNDLE_ID.quicklook"
TEAM_ID="${TEAM_ID:-}"
export VERSION BUILD BUNDLE_ID TEAM_ID   # gen_project.sh / project.yml read these

APP=XenScalePreview
EXT=XenScalePreviewExtension
EXT_ID="$BUNDLE_ID.quicklook"
PROJ="$APP.xcodeproj"

# Everything generated by builds lives under build/; dist/ only holds distributable zips.
BUILD_DIR=build
DIST_DIR=dist
DERIVED="$BUILD_DIR/dd"            # Xcode DerivedData (instead of ~/Library/Developer/Xcode/DerivedData)
ARCHIVES="$BUILD_DIR/archives"     # *.xcarchive
EXPORTS="$BUILD_DIR/export"        # exported .ipa / .pkg / .app
PLISTS="$BUILD_DIR/plists"         # generated ExportOptions plists

die() { echo "error: $*" >&2; exit 1; }
require_macos()  { [[ "$(uname)" == Darwin ]] || die "this script runs on macOS only."; }
require_xcode()  { command -v xcodebuild >/dev/null || die "xcodebuild not found. Install Xcode."; }
require_team()   { [[ -n "$TEAM_ID" ]] || die "set TEAM_ID to your Apple Developer team ID."; }

# xc_archive <scheme> <destination> <archive path>
xc_archive() {
  rm -rf "$3"; mkdir -p "$(dirname "$3")"
  xcodebuild -project "$PROJ" -scheme "$1" -configuration Release \
    -destination "$2" -archivePath "$3" -derivedDataPath "$DERIVED" \
    -allowProvisioningUpdates DEVELOPMENT_TEAM="$TEAM_ID" archive -quiet
}

# xc_export <archive> <export dir> <method> [export|upload]
xc_export() {
  local archive="$1" out="$2" method="$3" dest="${4:-export}"
  local plist="$PLISTS/ExportOptions-$(basename "$out")-$method.plist" symbols=""
  [[ "$method" == app-store-connect ]] && symbols="<key>uploadSymbols</key><true/>"
  mkdir -p "$PLISTS"; rm -rf "$out"
  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>method</key><string>$method</string>
  <key>destination</key><string>$dest</string>
  <key>teamID</key><string>$TEAM_ID</string>
  <key>signingStyle</key><string>automatic</string>
  $symbols
</dict></plist>
PLIST
  xcodebuild -exportArchive -archivePath "$archive" -exportPath "$out" \
    -exportOptionsPlist "$plist" -allowProvisioningUpdates
}
